"""empty message

Revision ID: 0d83bfa291bb
Revises: 
Create Date: 2025-03-12 22:29:22.036816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d83bfa291bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('location', mysql.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
