"""Initial migration

Revision ID: 2be3a670258b
Revises: 
Create Date: 2025-03-31 21:49:32.471087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2be3a670258b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emotion_type', sa.String(length=100), nullable=True))
        batch_op.alter_column('analyze',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', mysql.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('analyze',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('emotion_type')

    # ### end Alembic commands ###
